'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';

type User={id:string;username:string;role:'ADMIN'|'MEMBER'};
type Any=Record<string,any>;
async function request(path:string, method='GET', body?:Any) {
  const res=await fetch('/api/'+path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store'});
  const data=await res.json();
  if (!res.ok) throw new Error(data.error||'操作失败');
  return data;
}
const nav=[['/today','今天','◉'],['/points','积分','◈'],['/rewards','奖励','◇'],['/history','记录','▤']];
export function Shell({route}:{route:string}) {
  const [user,setUser]=useState<User|null>(null),[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const load=useCallback(async()=>{
    try { const me=await request('auth/me'); setUser(me); if(route==='/login'){setData(null);return;}
      if(route.startsWith('/admin')&&me.role!=='ADMIN'){location.href='/today';return;}
      const target=route==='/rewards/mine'?'rewards/mine':route==='/admin'?'admin/overview':route==='/admin/preview'?'admin/users':route.slice(1);
      setData(await request(target)); setError('');
    } catch(e) { if((e as Error).message==='请先登录'&&route!=='/login'){location.href='/login';return;} setError((e as Error).message); }
    finally {setLoading(false);}
  },[route]);
  useEffect(()=>{void load();},[load]);
  async function act(path:string, body?:Any, method='POST') { try {setError('');const result=await request(path,method,body);setNotice(result.nextStep?`已完成，下一步：${result.nextStep.text}`:'已完成');setTimeout(()=>setNotice(''),4000);await load();return true;}catch(e){setError((e as Error).message);return false;} }
  if(route==='/login') return <Login />;
  if(loading) return <main className="loading">加载中…</main>;
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">✳</span><div>ActionPoints<small>把开始变成进步</small></div></div><nav>{nav.map(([href,label,icon])=><Link className={route===href?'active':''} href={href} key={href}><span>{icon}</span>{label}</Link>)}<Link className={route==='/rewards/mine'?'active':''} href="/rewards/mine"><span>▣</span>我的奖励</Link>{user?.role==='ADMIN'&&<><Link className={route==='/admin/preview'?'active':''} href="/admin/preview"><span>👀</span>成员前台预览</Link><Link className={route==='/admin'?'active':''} href="/admin"><span>⚙</span>管理后台</Link></>}</nav><div className="sidebar-foot"><span>{user?.username}</span><button className="text-button" onClick={async()=>{await request('auth/logout','POST');location.href='/login';}}>退出</button></div></aside>
    <main className="main"><div className="topline"><span>家庭行动积分</span><button className="theme-toggle" onClick={()=>{document.documentElement.classList.toggle('dark');localStorage.setItem('ap-theme',document.documentElement.classList.contains('dark')?'dark':'light');}}>◐ <span>切换主题</span></button></div>
      {error&&<div className="alert" role="alert">{error}</div>}{notice&&<div className="toast">{notice} ✦</div>}
      {route==='/today'&&<Today data={data} onComplete={(id,stepId)=>act(stepId?'actions/step':'actions/complete',stepId?{actionId:id,stepId}:{actionId:id})}/>}
      {route==='/points'&&<Points data={data}/>}
      {route==='/rewards'&&<Rewards data={data} onRedeem={id=>act('rewards/redeem',{rewardId:id})}/>}
      {route==='/rewards/mine'&&<Mine data={data} onUse={id=>act('rewards/use',{redemptionId:id})}/>}
      {route==='/history'&&<History data={data}/>}
      {route==='/admin'&&user?.role==='ADMIN'&&<Admin onAct={act}/>}
      {route==='/admin/preview'&&user?.role==='ADMIN'&&<AdminPreview users={data||[]}/>}
    </main><nav className="mobile-nav">{nav.map(([href,label,icon])=><Link className={route===href?'active':''} href={href} key={href}><span>{icon}</span>{label}</Link>)}{user?.role==='ADMIN'&&<Link href="/admin" className={route==='/admin'?'active':''}><span>⚙</span>管理</Link>}</nav>
    <ThemeInit/>
  </div>;
}
function ThemeInit(){useEffect(()=>{if(localStorage.getItem('ap-theme')==='dark')document.documentElement.classList.add('dark');},[]);return null;}
function Login(){const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="login-page"><form className="login-card" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const me=await request('auth/login','POST',{username,password});location.href=me.role==='ADMIN'?'/admin':'/today';}catch(err){setError((err as Error).message);setBusy(false);}}}><div className="brand login-brand"><span className="brand-mark">✳</span><div>ActionPoints<small>把开始变成进步</small></div></div><h1>欢迎回来</h1><p>成员进入“今天”，管理员进入管理后台。</p>{error&&<div className="alert">{error}</div>}<label>用户名<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>密码<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary" disabled={busy}>登录</button></form></div>}
function Heading({eyebrow,title,sub}:{eyebrow:string;title:string;sub?:string}){return <header className="page-heading"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{sub&&<p>{sub}</p>}</header>}
function Today({data,onComplete,readOnly=false,embedded=false}:{data:any;onComplete:(id:string,stepId?:string)=>void;readOnly?:boolean;embedded?:boolean}){if(!data)return null;return <>{!embedded&&<Heading eyebrow={data.date} title="今天，从第一步开始" sub="做完一步，下一步就会出现。"/>}<div className="stats"><Stat label="当前积分" value={data.balance} suffix="分"/><Stat label="今日获得" value={data.earned} suffix="分"/><Stat label="已完成行动" value={data.completed} suffix="项"/></div><div className="section-title"><h2>今日行动</h2><span>{data.actions.length} 项安排</span></div><div className="action-grid">{data.actions.map((a:any)=><article className={'action-card '+(a.done?'done':'')} key={a.id}><div className="card-top"><span className="action-icon">{a.icon}</span><span className="time">{a.scheduledTime||'今天'}</span></div><h3>{a.name}</h3>{a.stepCount>0?<><div className="pattern-progress">{a.done?'全部完成':`第 ${a.progressCount+1} / ${a.stepCount} 步`} · 已得 {a.steps.slice(0,a.progressCount).reduce((n:number,s:any)=>n+s.points,0)} / {a.points} 分</div><div className="progress-track"><span style={{width:`${100*a.progressCount/a.stepCount}%`}}/></div>{a.currentStep&&<div className="first-step"><small>现在做这一步</small><strong>👉 {a.currentStep.text}</strong></div>}{a.progressCount>0&&<details className="completed-steps"><summary>已完成的步骤</summary>{a.steps.slice(0,a.progressCount).map((s:any)=><div key={s.id}>✓ {s.text} <span>+{s.points}</span></div>)}</details>}</>:a.firstStep&&<div className="first-step"><small>第一步</small><strong>👉 {a.firstStep}</strong></div>}{a.description&&<p>{a.description}</p>}<button disabled={readOnly||a.done||data.settled} className={a.done?'completed':'primary'} onClick={()=>onComplete(a.id,a.currentStep?.id)}>{a.done?'✓ 已完成':a.currentStep?`完成这一步 +${a.currentStep.points}`:`完成 +${a.points}`}</button></article>)}</div>{!data.actions.length&&<div className="empty">今天还没有安排的行动。管理员可以在 Pattern 页面逐步创建并分配。</div>}{data.settled&&<div className="hint">今日已结算，明天继续。</div>}</>}
function AdminPreview({users}:{users:any[]}){const members=useMemo(()=>users.filter(u=>u.role==='MEMBER'&&u.active),[users]);const [selected,setSelected]=useState(''),[preview,setPreview]=useState<any>(null),[error,setError]=useState('');useEffect(()=>{if(!selected&&members.length)setSelected(members[0].id);},[selected,members]);useEffect(()=>{if(!selected)return;let cancelled=false;setPreview(null);void request('admin/preview?userId='+encodeURIComponent(selected)).then(data=>{if(!cancelled){setPreview(data);setError('');}}).catch(e=>{if(!cancelled)setError((e as Error).message);});return()=>{cancelled=true;};},[selected]);return <><Heading eyebrow="MEMBER VIEW" title="成员前台预览" sub="这里展示成员打开应用后看到的“今天”。预览只读；实际完成步骤请用成员账号登录。"/><div className="preview-toolbar"><label>查看谁的界面<select value={selected} onChange={e=>setSelected(e.target.value)}>{members.map(u=><option value={u.id} key={u.id}>{u.username}</option>)}</select></label><div className="preview-actions"><Link className="outline" href="/admin">返回管理后台</Link><button className="primary" onClick={async()=>{await request('auth/logout','POST');location.href='/login';}}>切换成员账号登录</button></div></div>{!members.length&&<div className="empty">还没有成员，请先在管理后台添加成员。</div>}{error&&<div className="alert" role="alert">{error}</div>}{preview&&<><div className="preview-note">正在预览 {preview.member.username} 的前台 · 今天 {preview.today.date} · 仅查看</div><Today data={preview.today} onComplete={()=>{}} readOnly embedded/></>}</>}
function Stat({label,value,suffix}:{label:string;value:number;suffix:string}){return <div className="stat"><small>{label}</small><strong>{value}<em>{suffix}</em></strong></div>}
function Points({data}:{data:any}){if(!data)return null;const tx=data.transactions as any[],today=data.today as string;const d=new Date(today+'T12:00:00Z'),dow=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-dow);const weekStart=d.toISOString().slice(0,10);const periods=[['今日',(v:string)=>v===today],['本周',(v:string)=>v>=weekStart&&v<=today],['本月',(v:string)=>v.slice(0,7)===today.slice(0,7)]] as const;return <><Heading eyebrow="POINTS" title="每一分都有来处" sub="积分从行动中积累，也能换成你喜欢的奖励。"/><div className="balance-hero"><span>可用积分</span><strong>{data.balance}</strong><span>POINTS</span></div><div className="stats">{periods.map(([label,matches])=>{const list=tx.filter(t=>matches(t.localDate));return <div className="stat" key={label}><small>{label}</small><div className="stat-row"><span>获得 <b>+{list.filter(t=>t.amount>0).reduce((n,t)=>n+t.amount,0)}</b></span><span>消费 <b>{-list.filter(t=>t.amount<0).reduce((n,t)=>n+t.amount,0)}</b></span></div></div>})}</div><div className="section-title"><h2>积分流水</h2><span>全部记录</span></div><div className="list">{tx.map(t=><div className="list-row" key={t.id}><div><strong>{t.sourceName}</strong><small>{new Date(t.createdAt).toLocaleString('zh-CN')} · {t.note||t.type}</small></div><b className={t.amount>0?'positive':''}>{t.amount>0?'+':''}{t.amount}</b></div>)}</div>{!tx.length&&<div className="empty">还没有积分记录。</div>}</>}
function Rewards({data,onRedeem}:{data:any;onRedeem:(id:string)=>void}){if(!data)return null;return <><Heading eyebrow="REWARD STORE" title="奖励商店" sub="攒下的积分，可以换成真正想要的时刻。"/><Link className="sub-link" href="/rewards/mine">查看我的奖励 →</Link><div className="action-grid">{data.map((r:any)=><article className="reward-card" key={r.id}><div className="reward-icon">{r.icon}</div><h3>{r.name}</h3><p>{r.description||'给自己一个小小的奖励。'}</p><div className="reward-foot"><span>{r.cost} <small>积分</small></span><button className="primary" disabled={r.stock===0} onClick={()=>onRedeem(r.id)}>{r.stock===0?'已兑完':'兑换'}</button></div></article>)}</div>{!data.length&&<div className="empty">还没有定好家庭奖励。请先一起商量奖励内容、使用限制和需要多少积分，再由管理员添加。</div>}</>}
function Mine({data,onUse}:{data:any;onUse:(id:string)=>void}){if(!data)return null;return <><Heading eyebrow="MY REWARDS" title="我的奖励" sub="兑换后，想用的时候再点击使用。"/><div className="list">{data.map((r:any)=><div className="list-row" key={r.id}><div><strong>{r.rewardNameSnapshot}</strong><small>{new Date(r.redeemedAt).toLocaleDateString('zh-CN')} · {r.costSnapshot} 积分</small></div>{r.status==='AVAILABLE'?<button className="primary small" onClick={()=>onUse(r.id)}>使用</button>:<span className="muted">{r.status==='USED'?'已使用':'已取消'}</span>}</div>)}</div>{!data.length&&<div className="empty">还没有兑换过奖励。</div>}</>}
function History({data}:{data:any}){const [range,setRange]=useState<'day'|'week'|'month'>('day');if(!data)return null;const rows=data.settlements as any[];const key=(d:string)=>range==='day'?d:range==='month'?d.slice(0,7):(()=>{const date=new Date(d+'T12:00:00Z'),dow=(date.getUTCDay()+6)%7;date.setUTCDate(date.getUTCDate()-dow);return date.toISOString().slice(0,10)})(),groups=new Map<string,any>();for(const row of [...rows].reverse()){const k=key(row.localDate),v=groups.get(k)||{label:k,earned:0,spent:0,net:0,closing:0,days:[]};v.earned+=row.earnedPoints;v.spent+=row.spentPoints;v.net+=row.netPoints;v.closing=row.closingBalance;v.days.push(row.localDate);groups.set(k,v);}return <><Heading eyebrow="HISTORY" title="一步一步，留下轨迹" sub="查看每天的结算和开始行动的时间趋势。"/><div className="tabs">{[['day','按日'],['week','按周'],['month','按月']].map(([v,l])=><button className={range===v?'selected':''} key={v} onClick={()=>setRange(v as any)}>{l}</button>)}</div><div className="list">{[...groups.values()].reverse().map(g=><details className="history-item" key={g.label}><summary><strong>{g.label}</strong><span>获得 +{g.earned}　消费 {g.spent}　净变化 {g.net>=0?'+':''}{g.net}　余额 {g.closing}</span></summary><div className="history-detail">{data.transactions.filter((t:any)=>g.days.includes(t.localDate)).map((t:any)=><div key={t.id}>{t.sourceName}<b>{t.amount>0?'+':''}{t.amount}</b></div>)}</div></details>)}</div>{!rows.length&&<div className="empty">结算记录会在每天结束后显示。</div>}<div className="section-title"><h2>开始时间趋势</h2><span>最近 30 条</span></div><div className="list">{data.completions.slice(0,30).map((c:any,i:number)=><div className="list-row" key={i}><div><strong>{c.actionNameSnapshot}</strong><small>{c.localDate}</small></div><span>{Math.round(c.startupLatencySeconds/60)} 分钟</span></div>)}</div></>}

const adminTabs=[['overview','总览'],['users','成员'],['patterns','Pattern'],['actions','行动'],['bonus','加分'],['rewards','奖励'],['adjust','积分调整'],['settlements','结算'],['settings','设置'],['export','导出']];
function Admin({onAct}:{onAct:(path:string,body?:Any,method?:string)=>Promise<boolean>}){
  const [tab,setTab]=useState('overview'),[items,setItems]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[actions,setActions]=useState<any[]>([]),[bonuses,setBonuses]=useState<any[]>([]),[form,setForm]=useState<Any>({}),[busy,setBusy]=useState(false),[patternEdit,setPatternEdit]=useState<any>(null);
  const refresh=useCallback(async()=>{try{const [u,a,b]=await Promise.all([request('admin/users'),request('admin/actions'),request('admin/bonus')]);setUsers(u);setActions(a);setBonuses(b);if(['overview','users','actions','bonus','rewards','settlements','settings'].includes(tab))setItems(await request('admin/'+tab));}catch{}},[tab]);
  useEffect(()=>{void refresh();setForm({});},[refresh]);
  async function submit(path:string,body:Any,method='POST'){setBusy(true);const saved=await onAct(path,body,method);if(saved){await refresh();setForm({});}setBusy(false);return saved;}
  const field=(label:string,name:string,type='text',placeholder='')=><label>{label}<input type={type} placeholder={placeholder} value={form[name]??''} onChange={e=>setForm({...form,[name]:e.target.value})}/></label>;
  const check=(label:string,name:string,def=true)=><label className="checkbox"><input type="checkbox" checked={form[name]??def} onChange={e=>setForm({...form,[name]:e.target.checked})}/>{label}</label>;
  const select=(label:string,name:string,options:any[],display=(v:any)=>v.username)=><label>{label}<select value={form[name]??''} onChange={e=>setForm({...form,[name]:e.target.value})}><option value="">请选择</option>{options.map(x=><option key={x.id} value={x.id}>{display(x)}</option>)}</select></label>;
  return <><Heading eyebrow="ADMIN" title="管理家庭空间" sub="这里设置规则；成员登录后会进入自己的“今天”页面。"/><div className="admin-intro"><div><strong>想看成员使用的前台？</strong><span>选择一个家庭成员，查看他今天会看到的步骤和积分。</span></div><Link className="primary" href="/admin/preview">查看成员前台 →</Link></div><div className="admin-tabs">{adminTabs.map(([v,l])=><button className={tab===v?'selected':''} key={v} onClick={()=>setTab(v)}>{l}</button>)}</div>
    {tab==='patterns'&&<><div className="section-title"><h2>一步一步的 Pattern</h2><span>点「查看与编辑」可直接看到步骤</span></div><div className="list pattern-list">{actions.filter(a=>a.steps?.length).map(a=><div className="pattern-list-item" key={a.id}><div className="list-row"><div><strong>{a.icon} {a.name}</strong><small>{a.steps.length} 步 · 共 {a.points} 分 · {a.enabled?'启用':'停用'}</small></div><button className="outline small" aria-expanded={patternEdit?.id===a.id} onClick={()=>setPatternEdit(patternEdit?.id===a.id?null:a)}>{patternEdit?.id===a.id?'收起详情':'查看与编辑'}</button></div>{patternEdit?.id===a.id&&<PatternWizard key={a.id} initial={a} startStage={1} autoFocus users={users.filter(u=>u.role==='MEMBER'&&u.active)} onNew={()=>setPatternEdit(null)} onSave={async payload=>{const ok=await submit('admin/patterns',payload,'PATCH');if(ok)setPatternEdit(null);return ok;}}/>}</div>)}</div>{!patternEdit&&<PatternWizard key="new" initial={null} users={users.filter(u=>u.role==='MEMBER'&&u.active)} onNew={()=>setPatternEdit(null)} onSave={async payload=>submit('admin/patterns',payload,'POST')}/>}</>}
    {tab==='overview'&&<><div className="section-title"><h2>今天的家庭概览</h2></div><div className="list">{items.map(u=><div className="list-row" key={u.id}><div><strong>{u.username}</strong><small>{u.role==='ADMIN'?'管理员':'成员'} · 完成 {u.completed} 项</small></div><b>{u.balance} 分</b></div>)}</div></>}
    {tab==='users'&&<><div className="section-title"><h2>成员</h2></div><div className="list">{items.map(u=><div className="list-row" key={u.id}><div><strong>{u.username}</strong><small>{u.role} · {u.active?'正常':'停用'}</small></div><button className="outline small" onClick={()=>setForm({id:u.id,role:u.role,active:u.active})}>编辑</button></div>)}</div><div className="editor"><h3>{form.id?'编辑成员':'添加成员'}</h3><div className="form-grid">{!form.id&&field('用户名','username')}{field(form.id?'新密码（留空不修改）':'密码（至少 12 位）','password','password')}<label>角色<select value={form.role??'MEMBER'} onChange={e=>setForm({...form,role:e.target.value})}><option value="MEMBER">成员</option><option value="ADMIN">管理员</option></select></label>{form.id&&check('账号启用','active')}</div><button className="primary" disabled={busy} onClick={()=>submit('admin/users',form,form.id?'PATCH':'POST')}>保存成员</button></div></>}
    {tab==='actions'&&<><div className="section-title"><h2>行动</h2></div><div className="list">{items.map(a=><div className="list-row" key={a.id}><div><strong>{a.icon} {a.name}</strong><small>+{a.points} · {a.scheduledTime||'全天'} · {a.enabled?'启用':'停用'} · 已分配 {a.assignments?.filter((x:any)=>x.enabled).length||0} 人</small></div><button className="outline small" onClick={()=>{if(a.steps?.length){setPatternEdit(a);setTab('patterns');}else setForm(a);}}>编辑</button></div>)}</div><div className="editor"><h3>{form.id?'编辑单次行动':'新增单次行动'}</h3><p>需要连续多步的行动，请到 Pattern 按问答创建。</p><div className="form-grid">{field('名称','name')}{field('Emoji','icon')}{field('第一步','firstStep')}{field('说明','description')}{field('积分','points','number')}{field('计划时间','scheduledTime','time')}{field('重复星期（0=周日）','repeatRule','text','0,1,2,3,4,5,6')}{field('排序','sortOrder','number')}{check('启用','enabled')}{check('提醒预留','reminderEnabled',false)}{field('提前提醒分钟','reminderBeforeMinutes','number')}{check('过渡预留','transitionEnabled',false)}{field('过渡分钟','transitionDurationMinutes','number')}{field('过渡提示','transitionInstruction')}</div><button className="primary" disabled={busy} onClick={()=>submit('admin/actions',form,form.id?'PATCH':'POST')}>保存行动</button></div><div className="editor"><h3>分配行动</h3><div className="form-grid">{select('行动','assignActionId',actions,(v:any)=>v.name)}{select('成员','assignUserId',users.filter(u=>u.role==='MEMBER'))}{check('允许领取','assignEnabled')}</div><button className="outline" disabled={busy} onClick={()=>submit('admin/assign',{actionId:form.assignActionId,userId:form.assignUserId,enabled:form.assignEnabled??true})}>保存分配</button></div></>}
    {tab==='bonus'&&<><div className="section-title"><h2>加分规则</h2></div><div className="list">{items.map(b=><div className="list-row" key={b.id}><strong>{b.icon} {b.name} · +{b.points}</strong><button className="outline small" onClick={()=>setForm(b)}>编辑</button></div>)}</div><div className="editor"><h3>{form.id?'编辑规则':'新增规则'}</h3><div className="form-grid">{field('名称','name')}{field('Emoji','icon')}{field('积分','points','number')}{field('排序','sortOrder','number')}{check('启用','enabled')}</div><button className="primary" disabled={busy} onClick={()=>submit('admin/bonus',form,form.id?'PATCH':'POST')}>保存规则</button></div><div className="editor"><h3>发放加分</h3><div className="form-grid">{select('成员','awardUserId',users.filter(u=>u.role==='MEMBER'))}{select('规则','bonusId',bonuses,(v:any)=>v.name)}{field('备注','note')}</div><button className="outline" disabled={busy} onClick={()=>submit('admin/bonus/award',{userId:form.awardUserId,bonusId:form.bonusId,note:form.note})}>发放</button></div></>}
    {tab==='rewards'&&<><div className="section-title"><h2>奖励</h2></div><div className="editor"><h3>先对照行动积分，再定奖励价格</h3><p>下方是按当前启用行动计算的每周最高积分，实际获得取决于完成情况。奖励价格建议和家人一起讨论；现有奖品只是演示，可随时编辑或停用。</p><div className="reward-calibration">{users.filter(u=>u.role==='MEMBER'&&u.active).map(u=>{const weekly=actions.filter(a=>a.enabled&&a.assignments?.some((x:any)=>x.userId===u.id&&x.enabled)).reduce((n,a)=>n+a.points*a.repeatRule.split(',').length,0);const cost=Number(form.cost)||0;return <div key={u.id}><strong>{u.username}</strong><span>每周最多 {weekly} 分{cost>0&&weekly>0?` · 此奖励最快约 ${Math.ceil(cost/weekly*7)} 天可兑换`:''}</span></div>;})}</div></div><div className="list">{items.map(r=><div className="list-row" key={r.id}><div><strong>{r.icon} {r.name}</strong><small>{r.cost} 积分 · 库存 {r.stock??'不限'} · {r.enabled?'启用':'停用'}</small></div><button className="outline small" onClick={()=>setForm(r)}>编辑</button></div>)}</div><div className="editor"><h3>{form.id?'编辑奖励':'新增奖励'}</h3><p>把奖励写具体：能换到什么、多久、何时使用、有没有次数限制。确定后再填价格。</p><div className="form-grid">{field('名称','name')}{field('Emoji','icon')}{field('具体内容与使用限制','description')}{field('兑换所需积分','cost','number')}{field('库存（留空不限）','stock','number')}{field('排序','sortOrder','number')}{check('启用','enabled')}{check('可重复兑换','repeatable')}</div><button className="primary" disabled={busy} onClick={()=>submit('admin/rewards',form,form.id?'PATCH':'POST')}>保存奖励</button></div></>}
    {tab==='adjust'&&<><div className="editor"><h3>手工调整积分</h3><p>输入正数加分，负数扣分。每次调整都写入流水。</p><div className="form-grid">{select('成员','userId',users)}{field('分值','amount','number')}{field('原因（必填）','note')}</div><button className="primary" disabled={busy} onClick={()=>submit('admin/adjust',form)}>确认调整</button></div><div className="editor"><h3>撤销误领行动</h3><CompletionList onSubmit={id=>submit('admin/reverse',{completionId:id})}/></div><div className="editor"><h3>撤销尚未做完的 Pattern</h3><ProgressList onSubmit={(userId,actionId,localDate)=>submit('admin/progress/reverse',{userId,actionId,localDate})}/></div><div className="editor"><h3>取消未使用兑换</h3><RedemptionList onSubmit={id=>submit('admin/rewards/cancel',{redemptionId:id})}/></div></>}
    {tab==='settlements'&&<><div className="editor"><h3>手动结算</h3><p>结算后，当天不再接受新的积分操作。</p><div className="form-grid">{select('成员','userId',users)}{field('日期','localDate','date')}</div><button className="primary" disabled={busy} onClick={()=>submit('admin/settlements',form)}>结算</button></div><div className="list">{items.map(s=><div className="list-row" key={s.id}><div><strong>{s.user.username} · {s.localDate}</strong><small>行动 {s.completedActionCount} 项 · 获得 {s.earnedPoints} · 消费 {s.spentPoints} · {s.settlementType}</small></div><b>{s.closingBalance} 分</b></div>)}</div></>}
    {tab==='settings'&&<div className="editor"><h3>系统设置</h3><div className="form-grid">{field('每日自动结算时间','settlementTime','time','22:30')}{field('每日奖励门槛（0 关闭）','dailyBonusThreshold','number','0')}{field('每日奖励积分','dailyBonusPoints','number','0')}</div><button className="primary" disabled={busy} onClick={()=>submit('admin/settings',form,'PATCH')}>保存设置</button><div className="hint">当前设置：{items.map(s=>`${s.key}=${s.value}`).join(' · ')||'默认值'}</div></div>}
    {tab==='export'&&<div className="editor"><h3>导出 CSV</h3><p>文件包含家庭成员的记录，请妥善保存。</p><div className="export-links"><a className="outline" href="/api/admin/export?kind=transactions">积分流水</a><a className="outline" href="/api/admin/export?kind=actions">行动完成</a><a className="outline" href="/api/admin/export?kind=settlements">每日结算</a></div></div>}
  </>;
}
function CompletionList({onSubmit}:{onSubmit:(id:string)=>void}){const [items,setItems]=useState<any[]>([]);useEffect(()=>{void request('admin/completions').then(setItems);},[]);return <div className="list compact">{items.filter(c=>!c.reversedAt).slice(0,30).map(c=><div className="list-row" key={c.id}><div><strong>{c.user.username} · {c.actionNameSnapshot}</strong><small>{c.localDate} · +{c.pointsAwarded}</small></div><button className="outline small" onClick={()=>onSubmit(c.id)}>撤销</button></div>)}</div>}
function ProgressList({onSubmit}:{onSubmit:(userId:string,actionId:string,localDate:string)=>void}){const [items,setItems]=useState<any[]>([]),[full,setFull]=useState<any[]>([]);useEffect(()=>{void Promise.all([request('admin/step-completions'),request('admin/completions')]).then(([a,b])=>{setItems(a);setFull(b);});},[]);const groups=new Map<string,any>();for(const s of items){const key=`${s.userId}|${s.actionId}|${s.localDate}`;if(full.some(c=>c.userId===s.userId&&c.actionId===s.actionId&&c.localDate===s.localDate&&!c.reversedAt))continue;const row=groups.get(key)||{...s,count:0,points:0};row.count++;row.points+=s.pointsAwarded;groups.set(key,row);}return <div className="list compact">{[...groups.values()].slice(0,30).map(s=><div className="list-row" key={s.id}><div><strong>{s.user.username} · {s.action.name}</strong><small>{s.localDate} · 已完成 {s.count} 步 · +{s.points} 分</small></div><button className="outline small" onClick={()=>onSubmit(s.userId,s.actionId,s.localDate)}>撤销</button></div>)}{!groups.size&&<div className="empty">没有进行中的 Pattern。</div>}</div>}
function RedemptionList({onSubmit}:{onSubmit:(id:string)=>void}){const [items,setItems]=useState<any[]>([]);useEffect(()=>{void request('admin/redemptions').then(setItems);},[]);return <div className="list compact">{items.filter(r=>r.status==='AVAILABLE').slice(0,30).map(r=><div className="list-row" key={r.id}><div><strong>{r.user.username} · {r.rewardNameSnapshot}</strong><small>{r.costSnapshot} 积分</small></div><button className="outline small" onClick={()=>onSubmit(r.id)}>取消</button></div>)}</div>}

const familyTopics=[['吃饭','🍽️'],['戴眼镜','👓'],['刷牙','🪥'],['洗澡','🚿'],['做作业','📚'],['出门','🎒']] as const;
const weekdays=[['1','周一'],['2','周二'],['3','周三'],['4','周四'],['5','周五'],['6','周六'],['0','周日']] as const;
function PatternWizard({initial,users,onNew,onSave,startStage=0,autoFocus=false}:{initial:any;users:any[];onNew:()=>void;onSave:(payload:Any)=>Promise<boolean>;startStage?:number;autoFocus?:boolean}){
  const blank=()=>({name:'',icon:'✨',description:'',steps:[{text:'',points:0},{text:'',points:0}],scheduledTime:'',repeatRule:'0,1,2,3,4,5,6',userIds:users.map(u=>u.id),enabled:true});
  const editorRef=useRef<HTMLDivElement>(null);
  const [stage,setStage]=useState(startStage),[draft,setDraft]=useState<Any>(()=>initial?{id:initial.id,name:initial.name,icon:initial.icon,description:initial.description,steps:initial.steps.map((s:any)=>({id:s.id,text:s.text,points:s.points})),scheduledTime:initial.scheduledTime||'',repeatRule:initial.repeatRule,userIds:initial.assignments.filter((a:any)=>a.enabled).map((a:any)=>a.userId),enabled:initial.enabled}:blank()),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  useEffect(()=>{if(autoFocus)editorRef.current?.scrollIntoView({behavior:'smooth',block:'start'});},[autoFocus]);
  const steps=draft.steps as Any[],selectedDays=String(draft.repeatRule).split(',');
  const total=steps.reduce((n,s)=>n+(Number(s.points)||0),0);
  function changeStep(i:number,patch:Any){setDraft({...draft,steps:steps.map((s,j)=>j===i?{...s,...patch}:s)});}
  function next(){setError('');if(stage===0&&!String(draft.name).trim()){setError('先给这个 Pattern 起个名字');return;}if(stage===1&&(steps.length<2||steps.some(s=>!String(s.text).trim()))){setError('请写出至少两步，每一步都要有内容');return;}if(stage===2&&steps.some(s=>!Number.isInteger(Number(s.points))||Number(s.points)<0||Number(s.points)>1000)){setError('每一步的积分须为 0–1000 的整数');return;}if(stage===3&&!(draft.userIds as string[]).length){setError('请至少选择一位家庭成员');return;}setStage(Math.min(stage+1,4));}
  const answer=[`${draft.icon} ${draft.name||'未命名'}`,steps.map(s=>s.text).filter(Boolean).join(' → '),`每步独立记分，共 ${total} 分`,`${draft.scheduledTime||'全天'} · ${(draft.userIds as string[]).length} 位成员`];
  return <div className="pattern-wizard" ref={editorRef}><div className="wizard-top"><div><span className="eyebrow">{initial?`正在查看与编辑：${initial.name}`:'新建 Pattern'}</span><h3>{initial?'下面是这件事的步骤，可直接修改':'用对话把一件事拆成小步骤'}</h3></div>{initial&&<button className="outline small" onClick={()=>{onNew();setDraft(blank());setStage(0);setError('');}}>新增 Pattern</button>}</div><div className="wizard-trail">{answer.slice(0,stage).map((value,i)=><div className="dialogue-pair" key={i}><span>{['这件事叫什么？','要经过哪些步骤？','每步怎样计分？','什么时候、谁来做？'][i]}</span><strong>{value}</strong></div>)}</div><div className="wizard-question"><small>问题 {stage+1} / 5</small><h4>{['你想创建哪件事？','这件事要按什么顺序做？','每一步完成后给多少分？','这件事什么时候做，谁来做？','确认这个 Pattern'][stage]}</h4>
    {stage===0&&<><p>先从你们家重视的事情开始，也可以输入别的名字。</p><div className="topic-picks">{familyTopics.map(([name,icon])=><button className={draft.name===name?'selected':''} key={name} onClick={()=>setDraft({...draft,name,icon})}>{icon} {name}</button>)}</div><div className="form-grid"><label>行动名称<input value={draft.name} maxLength={100} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>图标<input value={draft.icon} maxLength={10} onChange={e=>setDraft({...draft,icon:e.target.value})}/></label></div><label>给家人的说明（可选）<input value={draft.description} maxLength={500} placeholder="为什么要做，或完成时的标准" onChange={e=>setDraft({...draft,description:e.target.value})}/></label></>}
    {stage===1&&<><p>一行写一个能看懂、能完成的动作。顺序就是“今天”里出现的顺序；点“下一步”可以修改每步积分。</p><div className="step-editor">{steps.map((s,i)=><div className="step-line" key={s.id||i}><span>{i+1}</span><input aria-label={`第 ${i+1} 步`} value={s.text} maxLength={200} placeholder={i===0?'例如：坐到书桌前':'下一步做什么？'} onChange={e=>changeStep(i,{text:e.target.value})}/><span className="step-points">+{s.points} 分</span><button aria-label="上移" title="上移" disabled={i===0} onClick={()=>{const copy=[...steps];[copy[i-1],copy[i]]=[copy[i],copy[i-1]];setDraft({...draft,steps:copy});}}>↑</button><button aria-label="下移" title="下移" disabled={i===steps.length-1} onClick={()=>{const copy=[...steps];[copy[i+1],copy[i]]=[copy[i],copy[i+1]];setDraft({...draft,steps:copy});}}>↓</button><button aria-label="删除步骤" title="删除" disabled={steps.length<=2} onClick={()=>setDraft({...draft,steps:steps.filter((_,j)=>j!==i)})}>×</button></div>)}</div><button className="outline small" disabled={steps.length>=20} onClick={()=>setDraft({...draft,steps:[...steps,{text:'',points:0}]})}>＋ 添加一步</button></>}
    {stage===2&&<><p>先给每步分值。也可以填 0：这一步只负责引导，不单独奖励。具体多少分由你们家决定。</p><div className="score-editor">{steps.map((s,i)=><label key={s.id||i}><span>{i+1}. {s.text}</span><input type="number" min="0" max="1000" step="1" value={s.points} onChange={e=>changeStep(i,{points:e.target.value})}/><em>分</em></label>)}</div><div className="score-total">这件事全部做完：<strong>{total} 分</strong></div></>}
    {stage===3&&<><p>可以选每天或某几天。计划时间可留空，表示全天可做。</p><div className="form-grid"><label>计划时间（可选）<input type="time" value={draft.scheduledTime} onChange={e=>setDraft({...draft,scheduledTime:e.target.value})}/></label><label className="checkbox"><input type="checkbox" checked={draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>立即启用</label></div><div className="wizard-label">哪几天重复？</div><div className="topic-picks">{weekdays.map(([value,label])=><button className={selectedDays.includes(value)?'selected':''} key={value} onClick={()=>{const next=selectedDays.includes(value)?selectedDays.filter(x=>x!==value):[...selectedDays,value];setDraft({...draft,repeatRule:next.length?next.sort().join(','):value});}}>{label}</button>)}</div><div className="wizard-label">适用哪些成员？</div><div className="topic-picks">{users.map(u=><button className={(draft.userIds as string[]).includes(u.id)?'selected':''} key={u.id} onClick={()=>setDraft({...draft,userIds:(draft.userIds as string[]).includes(u.id)?(draft.userIds as string[]).filter(x=>x!==u.id):[...draft.userIds,u.id]})}>{u.username}</button>)}</div>{!users.length&&<p>请先在“成员”中添加一位家庭成员。</p>}</>}
    {stage===4&&<><p>确认后会保存到家庭空间，成员在“今天”逐步完成。之后仍可编辑。</p><div className="pattern-review"><strong>{draft.icon} {draft.name}</strong><small>{draft.description}</small>{steps.map((s,i)=><div key={s.id||i}><span>{i+1}. {s.text}</span><b>+{s.points}</b></div>)}<footer>合计 {total} 分 · {draft.scheduledTime||'全天'} · {users.filter(u=>(draft.userIds as string[]).includes(u.id)).map(u=>u.username).join('、')}</footer></div></>}
    {error&&<div className="alert" role="alert">{error}</div>}<div className="wizard-buttons">{stage>0&&<button className="outline" onClick={()=>{setError('');setStage(stage-1);}}>上一步</button>}{stage<4?<button className="primary" onClick={next}>下一步 →</button>:<button className="primary" disabled={saving} onClick={async()=>{setSaving(true);const ok=await onSave({...draft,steps:steps.map(s=>({...s,points:Number(s.points)}))});setSaving(false);if(ok){setDraft(blank());setStage(0);}}}>保存 Pattern</button>}</div></div></div>;
}
