CREATE TYPE "Role" AS ENUM ('ADMIN','MEMBER');
CREATE TYPE "TxType" AS ENUM ('ACTION','BONUS','REWARD_PURCHASE','MANUAL_ADJUSTMENT','REVERSAL','DAILY_BONUS');
CREATE TYPE "RedemptionStatus" AS ENUM ('AVAILABLE','USED','CANCELLED');
CREATE TYPE "SettlementType" AS ENUM ('MANUAL','AUTO');

CREATE TABLE "User" ("id" TEXT PRIMARY KEY, "username" TEXT NOT NULL UNIQUE, "passwordHash" TEXT NOT NULL, "role" "Role" NOT NULL DEFAULT 'MEMBER', "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Session" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE, "tokenHash" TEXT NOT NULL UNIQUE, "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "LoginAttempt" ("id" TEXT PRIMARY KEY, "key" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "LoginAttempt_key_createdAt_idx" ON "LoginAttempt"("key","createdAt");
CREATE TABLE "Action" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "icon" TEXT NOT NULL DEFAULT '✨', "description" TEXT NOT NULL DEFAULT '', "firstStep" TEXT NOT NULL DEFAULT '', "points" INTEGER NOT NULL, "scheduledTime" TEXT, "repeatRule" TEXT NOT NULL DEFAULT '0,1,2,3,4,5,6', "reminderEnabled" BOOLEAN NOT NULL DEFAULT false, "reminderBeforeMinutes" INTEGER NOT NULL DEFAULT 10, "transitionEnabled" BOOLEAN NOT NULL DEFAULT false, "transitionDurationMinutes" INTEGER NOT NULL DEFAULT 5, "transitionInstruction" TEXT NOT NULL DEFAULT '', "enabled" BOOLEAN NOT NULL DEFAULT true, "sortOrder" INTEGER NOT NULL DEFAULT 0, "createdBy" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
ALTER TABLE "Action" ADD CONSTRAINT "Action_points_check" CHECK ("points" >= 0);
CREATE TABLE "ActionAssignment" ("id" TEXT PRIMARY KEY, "actionId" TEXT NOT NULL REFERENCES "Action"("id") ON DELETE CASCADE, "userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE, "enabled" BOOLEAN NOT NULL DEFAULT true, UNIQUE("actionId","userId"));
CREATE TABLE "ActionCompletion" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL REFERENCES "User"("id"), "actionId" TEXT NOT NULL REFERENCES "Action"("id"), "localDate" TEXT NOT NULL, "scheduledAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "startupLatencySeconds" INTEGER, "pointsAwarded" INTEGER NOT NULL, "actionNameSnapshot" TEXT NOT NULL, "reversedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "ActionCompletion_active_unique" ON "ActionCompletion"("userId","actionId","localDate") WHERE "reversedAt" IS NULL;
CREATE INDEX "ActionCompletion_userId_localDate_idx" ON "ActionCompletion"("userId","localDate");
CREATE TABLE "BonusRule" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "icon" TEXT NOT NULL DEFAULT '✨', "points" INTEGER NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, "sortOrder" INTEGER NOT NULL DEFAULT 0);
ALTER TABLE "BonusRule" ADD CONSTRAINT "BonusRule_points_check" CHECK ("points" > 0);
CREATE TABLE "PointTransaction" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL REFERENCES "User"("id"), "amount" INTEGER NOT NULL, "type" "TxType" NOT NULL, "sourceId" TEXT, "sourceName" TEXT NOT NULL, "note" TEXT NOT NULL DEFAULT '', "createdByUserId" TEXT, "localDate" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "PointTransaction" ADD CONSTRAINT "PointTransaction_amount_check" CHECK ("amount" <> 0);
CREATE INDEX "PointTransaction_userId_createdAt_idx" ON "PointTransaction"("userId","createdAt");
CREATE INDEX "PointTransaction_userId_localDate_idx" ON "PointTransaction"("userId","localDate");
CREATE UNIQUE INDEX "PointTransaction_daily_bonus_unique" ON "PointTransaction"("userId","localDate") WHERE "type" = 'DAILY_BONUS';
CREATE TABLE "Reward" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "icon" TEXT NOT NULL DEFAULT '🎁', "description" TEXT NOT NULL DEFAULT '', "cost" INTEGER NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, "repeatable" BOOLEAN NOT NULL DEFAULT true, "stock" INTEGER, "sortOrder" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
ALTER TABLE "Reward" ADD CONSTRAINT "Reward_cost_check" CHECK ("cost" > 0);
ALTER TABLE "Reward" ADD CONSTRAINT "Reward_stock_check" CHECK ("stock" IS NULL OR "stock" >= 0);
CREATE TABLE "RewardRedemption" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL REFERENCES "User"("id"), "rewardId" TEXT NOT NULL REFERENCES "Reward"("id"), "rewardNameSnapshot" TEXT NOT NULL, "costSnapshot" INTEGER NOT NULL, "status" "RedemptionStatus" NOT NULL DEFAULT 'AVAILABLE', "redeemedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "usedAt" TIMESTAMP(3), "cancelledAt" TIMESTAMP(3));
CREATE INDEX "RewardRedemption_userId_status_idx" ON "RewardRedemption"("userId","status");
CREATE TABLE "DailySettlement" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL REFERENCES "User"("id"), "localDate" TEXT NOT NULL, "completedActionCount" INTEGER NOT NULL, "actionPoints" INTEGER NOT NULL, "bonusPoints" INTEGER NOT NULL, "dailyBonusPoints" INTEGER NOT NULL, "earnedPoints" INTEGER NOT NULL, "spentPoints" INTEGER NOT NULL, "netPoints" INTEGER NOT NULL, "openingBalance" INTEGER NOT NULL, "closingBalance" INTEGER NOT NULL, "settledAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "settlementType" "SettlementType" NOT NULL, UNIQUE("userId","localDate"));
CREATE TABLE "Setting" ("key" TEXT PRIMARY KEY, "value" TEXT NOT NULL);
